num_cup = int(input("Write how many cups of coffee you will need:\n"))
print("For %i cups of coffee you will need:" % (num_cup))
print("%i ml of water" % (num_cup * 200))
print("%i ml of milk" % (num_cup * 50))
print("%i g of coffee beans" % (num_cup * 15))